export const dashboardDataModel = {
    campaignPerformance:

        [{
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'fb',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',


            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        },
        {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'fb',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'fb',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'fb',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        }, {
            checked: false,
            status: 'ACTIVE',
            compaignName: "Smart Display",
            budget: '8,000.00',
            type: 'google',
            clicks: '37,906',
            impr: '1,773,237',
            ctr: '2.14',

            spend: '62,670.45',
            avgCpc: '37,906',
            webConv: '7,773,237',
            convRate: 2.14,
            cpa: '62,670.45',
            actions: '--',
            socClicks: '--',
            follow: '--',
            replies: '--',
            retwe: '--',
            likes: '--',
            results: '--',
            cpr: '--',
            avgPos: '--',

        },
        ],


    allNetworks: [
        {

            source: "Total",
            imporessions: "9,766,878",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        },
        {

            source: "Adwords",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        }, {

            source: "facebook",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        }, {

            source: "Snapchat",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        }, {

            source: "Iron Source",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        }, {

            source: "Apple Search Ads",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8


        }, {
            source: "Vungle",
            imporessions: "2,345,238",
            clicks: "518,786",
            install: "76,989",
            cost: "809,874.00",
            revenue: "9,874.00",
            cvr: "12.54",
            ecpi: "4.54",
            roi14d: 3.8

        }],


    topNetwork: [{
        network: "FACEBOOK",
        clicks: "86,985",
        impr: "3,743,237",
        ctr: "2.14",
        spend: "54,670.45",
        avgCpc: "82,906",
        webConv: "3,783,287",
        convRate: "10.14",
        cpa: "56,670.45",
        actions: "--",
        socClick: "--",
        follow: "--",
        replies: "--",
        retwe: "--",
        likes: "--",
        results: "--",
        cpr: "--",
        avgPos: "--"

    },
    {

        network: "GOOGLE",
        clicks: "86,985",
        impr: "3,743,237",
        ctr: "2.14",
        spend: "54,670.45",
        avgCpc: "82,906",
        webConv: "3,783,287",
        convRate: "10.14",
        cpa: "56,670.45",
        actions: "--",
        socClick: "--",
        follow: "--",
        replies: "--",
        retwe: "--",
        likes: "--",
        results: "--",
        cpr: "--",
        avgPos: "--"

    }]



}